DROP TABLE IF EXISTS FOOD_ITEM_IN_MEAL_PLAN;
DROP TABLE IF EXISTS MEAL_PLAN_RECOMMENDATION;
DROP TABLE IF EXISTS MEAL_PLAN;
DROP TABLE IF EXISTS MEMBERSHIP_MODIFICATION;
DROP TABLE IF EXISTS FOOD_ITEM;
DROP TABLE IF EXISTS COURSE_REGISTRATION;
DROP TABLE IF EXISTS Course_in_area;
DROP TABLE IF EXISTS machine_in_Area;
DROP TABLE IF EXISTS PERSONAL_TRAINING;
DROP TABLE IF EXISTS CLEANING_RECORD;
DROP TABLE IF EXISTS REPORT;
DROP TABLE IF EXISTS GYM_SESSION;
DROP TABLE IF EXISTS JANITOR;
DROP TABLE IF EXISTS SALES;
DROP TABLE IF EXISTS MANAGER;
DROP TABLE IF EXISTS COACH;
DROP TABLE IF EXISTS COACH_EXPERIENCE;
DROP TABLE IF EXISTS STAFF;
DROP TABLE IF EXISTS Staff_Location;
DROP TABLE IF EXISTS MEMBERSHIP;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS Area;
DROP TABLE IF EXISTS locker;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE COURSE (
ID CHAR(20),
TITLE CHAR(20) NOT NULL,
DESCRIPTION CHAR(140),
PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER (
ID CHAR(20),
FIRST_NAME CHAR(30),
LAST_NAME CHAR(30),
PASSWORD CHAR(30),
ADDR CHAR(30),
DOB DATE,
GENDER CHAR(10),
PHONE CHAR(20),
EMAIL CHAR(30),
POSTAL_CODE CHAR(8),
PRIMARY KEY (ID)
);

CREATE TABLE Area (
ID CHAR(20),
Name CHAR(20),
AREA_SIZE CHAR(20),
PRIMARY KEY (ID)
);

CREATE TABLE COACH_EXPERIENCE (
YEARS INT,
COACH_LEVEL CHAR(10),
PRIMARY KEY (YEARS)
);

CREATE TABLE MEAL_PLAN (
ID CHAR(20),
NAME CHAR(20),
DESCRIPTION CHAR(140),
PRIMARY KEY (ID)
);


CREATE TABLE FOOD_ITEM (
NAME CHAR(20),
FAT INT,
CARBS INT,
PROTEIN INT,
CALORIES INT NOT NULL,
PRIMARY KEY (NAME)
);


CREATE TABLE Staff_Location(
Province CHAR(20),
City CHAR(20),
Postal_code CHAR(8),
PRIMARY KEY (Postal_code)
);

/***************************************************************/

CREATE TABLE MEMBERSHIP (
ID CHAR(20),
DATA_JOINED DATE,
DUE_DATE DATE,
PAYMENT_METHOD CHAR(60),
FEE CHAR(10),
CUSTOMER_ID CHAR(20),
PRIMARY KEY (ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE
);

CREATE TABLE LOCKER (
ID CHAR(20),
LOCKER_SIZE CHAR(10),
STATUS CHAR(10),
CUSTOMER_ID CHAR(20),
PRIMARY KEY (ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE
);

CREATE TABLE GYM_SESSION (
COURSE_ID CHAR(20) UNIQUE,
SESSION_NUMBER INT UNIQUE,
SCHEDULE CHAR(140),
SESSION_SIZE INT,
PRIMARY KEY (COURSE_ID, SESSION_NUMBER),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID) ON DELETE CASCADE
);


CREATE TABLE COURSE_REGISTRATION (
CUSTOMER_ID CHAR(20),
COURSE_ID CHAR(20),
SESSION_NUMBER INT,
PRIMARY KEY (CUSTOMER_ID, COURSE_ID, SESSION_NUMBER),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE,
FOREIGN KEY (COURSE_ID) REFERENCES GYM_SESSION(COURSE_ID) ON DELETE CASCADE,
FOREIGN KEY (SESSION_NUMBER) REFERENCES GYM_SESSION(SESSION_NUMBER) ON DELETE CASCADE
);

CREATE TABLE Course_in_area (
course_id CHAR(20),
area_id CHAR(20),
PRIMARY KEY (course_id, area_id),
FOREIGN KEY (course_id) REFERENCES Course(ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (area_id) REFERENCES Area(ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE machine_in_Area (
machine_ID CHAR(20),
Area_ID CHAR(20),
description CHAR(20),
PRIMARY KEY (machine_ID),
FOREIGN KEY (Area_ID) REFERENCES Area(ID) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE STAFF(
id CHAR(20),
firstName CHAR(30),
lastName CHAR(30),
password CHAR(30),
STAFF_SIN CHAR(20) NOT NULL,
month_salary REAL,
phone CHAR(20),
email CHAR(30),
address CHAR(30),
gender CHAR(10),
DOB DATE,
Postal_code CHAR(10),
PRIMARY KEY (id),
FOREIGN KEY (Postal_code) REFERENCES Staff_Location(Postal_code) ON DELETE CASCADE
);

CREATE TABLE COACH (
Staff_ID CHAR(20),
year_of_exp INT,
PRIMARY KEY (Staff_ID),
FOREIGN KEY (Staff_ID) REFERENCES staff(ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (year_of_exp) REFERENCES COACH_EXPERIENCE(YEARS) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SALES (
ID CHAR(20),
SALES_LEVEL CHAR(10),
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES STAFF(ID) ON DELETE CASCADE
);

CREATE TABLE MANAGER (
ID CHAR(20),
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES STAFF(ID) ON DELETE CASCADE
);


CREATE TABLE JANITOR (
ID CHAR(20),
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES STAFF(ID) ON DELETE CASCADE
);

CREATE TABLE PERSONAL_TRAINING (
CUSTOMER CHAR(20),
COACH CHAR(20),
SCHEDULE CHAR(140),
PRIMARY KEY (CUSTOMER, COACH),
FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER(ID) ON DELETE CASCADE,
FOREIGN KEY (COACH) REFERENCES COACH(STAFF_ID) ON DELETE CASCADE
);

CREATE TABLE MEMBERSHIP_MODIFICATION (
IDX INT,
MANAGER CHAR(20),
MEMBERSHIP_ID CHAR(20),
DESCRIPTION CHAR(50),
PRIMARY KEY (IDX),
FOREIGN KEY (MANAGER) REFERENCES MANAGER(ID) ON DELETE CASCADE,
FOREIGN KEY (MEMBERSHIP_ID) REFERENCES MEMBERSHIP(ID) ON DELETE CASCADE
);


CREATE TABLE FOOD_ITEM_IN_MEAL_PLAN (
PLAN_ID CHAR(20),
FOOD_ITEM CHAR(20),
QUANTITY INT,
PRIMARY KEY (PLAN_ID, FOOD_ITEM),
FOREIGN KEY (PLAN_ID) REFERENCES MEAL_PLAN(ID) ON DELETE CASCADE,
FOREIGN KEY (FOOD_ITEM) REFERENCES FOOD_ITEM(NAME) ON DELETE CASCADE
);

CREATE TABLE MEAL_PLAN_RECOMMENDATION (
PLAN_ID CHAR(10),
CUSTOMER_ID CHAR(20),
COACH_ID CHAR(20),
PRIMARY KEY (PLAN_ID, CUSTOMER_ID, COACH_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE,
FOREIGN KEY (PLAN_ID) REFERENCES MEAL_PLAN(ID) ON DELETE CASCADE,
FOREIGN KEY (COACH_ID) REFERENCES COACH(STAFF_ID) ON DELETE CASCADE
);



CREATE TABLE CLEANING_RECORD (
IDX INT,
JANITOR CHAR(20) NOT NULL,
AREA CHAR(20) NOT NULL,
CLEAN_DATE DATE,
PRIMARY KEY (IDX),
FOREIGN KEY (JANITOR) REFERENCES JANITOR(ID) ON DELETE CASCADE,
FOREIGN KEY (AREA) REFERENCES AREA(ID) ON DELETE CASCADE
);

CREATE TABLE REPORT (
REPORTER CHAR(20),
MANAGER CHAR(20),
PRIMARY KEY (REPORTER),
FOREIGN KEY (REPORTER) REFERENCES STAFF(ID) ON DELETE CASCADE,
FOREIGN KEY (MANAGER) REFERENCES MANAGER(ID) ON DELETE CASCADE
);






